# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: GdDS
has_binder: false
has_settings: false
kind: server
labextension_name: GdDS
project_short_description: A JupyterLab extension.
python_name: GdDS
repository: ''
test: true

