stages:
  - build

build_gdds:
  stage: build
  tags:
    - alpine
  image: alpine:latest
  cache:
    key: alpine-packages
    paths:
      - /var/cache/apk/
  before_script:
    - apk add --no-cache bash python3 py3-pip nodejs npm
    - apk add --no-cache gcc python3-dev musl-dev linux-headers
    - python3 -m venv /opt/venv
    - source /opt/venv/bin/activate
    - pip install hatch build
  script:
    - python -m build
    - ls -la dist/
  artifacts:
    paths:
      - dist/