name: Deploy

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: [self-hosted, test-deployment]
    environment: test-deployment

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock docker compose up -d --build local_lab